### PR TITLE
add to travis.yml the runtime repo in the deploy block

### PR DESCRIPTION
**Pull request by eweiter**
This PR is to lock down the Deploy step of the Travis.yml so that it only executes when the repo matches the "upstream" repo, 'incubator-openwhisk-runtime-docker'

### CODE REVIEW

**Comment by eweiter** [comment]
@csantanapr Please review

**Comment by rabbah** [comment]
this would prevent travis on forks?

**Comment by csantanapr** [comment]
@rabbah this makes it better working with forks. 

This just deals with the publish step, on master and tags. 

Travis will work on your fork if it happens, but will skip the publish

**Comment by csantanapr** [comment]
Thanks 👍  @rabbah  🚢 literally leaving the port right now..

**Pull request merged**
